Opal.queue(function(Opal) {/* Generated by Opal 1.5.0 */
  var nil = Opal.nil, a = nil, b = nil, c = nil, d = nil;

  Opal.add_stubs('[]=,[]');
  
  a = [];
  b = [10, 20, 30];
  b['$[]='](2, 40);
  c = b['$[]'](0);
  d = b['$[]'](-1);
  return nil;
});
