Opal.queue(function(Opal) {/* Generated by Opal 1.5.0 */
  var nil = Opal.nil, $hash2 = Opal.hash2, $hash = Opal.hash, a = nil, b = nil, c = nil;

  
  a = $hash2([], {});
  b = $hash(10, 20, 30, 40);
  c = $hash2(["hello"], {"hello": "world"});
  return nil;
});
