Opal.queue(function(Opal) {/* Generated by Opal 1.5.0 */
  var nil = Opal.nil, $rb_plus = Opal.rb_plus, a = nil, b = nil, c = nil, d = nil, e = nil;

  Opal.add_stubs('+,abs');
  
  a = -420;
  b = 6.9;
  c = $rb_plus(a, b);
  d = 999999999999999999;
  e = a.$abs();
  return nil;
});
