#!/usr/bin/env ruby

def parse_date(s)
  case s
  when %r[(\d\d\d\d)-(\d\d)-(\d\d)|(\d\d\d\d)/(\d\d)/(\d\d)|(\d\d)/(\d\d)/(\d\d\d\d)]
    [($1 || $4 || $9).to_i, ($2 || $5 || $8).to_i, ($3 || $6 || $7).to_i]
  end
end

%W[
  2015-05-25
  2016/06/26
  27/07/2017
].each do |s|
  p parse_date(s)
end
